# vim:set sw=2 ts=2 et:
---
image: docker:latest

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_BUILD_REF

before_script:
- docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY

build:
  stage: build
  tags:
  - docker

  script:
  - docker build --pull -t $IMAGE_TAG .
  - docker push $IMAGE_TAG
  - docker tag $IMAGE_TAG $CI_REGISTRY_IMAGE:latest
  - docker push $CI_REGISTRY_IMAGE:latest
