language: python
sudo: required
services:
- docker
addons:
  apt:
    packages:
    - docker-ce
script:
- ./travis-build.sh
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: nD52dwZB1fFyZ63IscwMIfVFryBkN/hknR4bfENhRDoNKJmy15PRPy0lc95obxq1NBPojWoYdeFkx31O1C2SMFmgHu0DRep8snn5LQdHIGjrxssF/2gCXuLj8RyDii1MjT6CEWS6Ni5yPu4rKDLO7JxSPwsCyyf3IqR8lofkuHaF/5cOpZdqTkkCPD0AfIP1ZJkxyDDernCbJJIs8S7M7QmHNhea8SgCYSk2mXkJNhChfXzxDQe1H8YRqJMfQaiY4x6k4fvaFkYN/CnQIR5fCxnmiCQUx56MMdL3EYbbcYDxiuow7VbaEgpVTSmqwRQEcW+toeZpuADx1nL6MMK2W25hESJdzMFWkTGr9ztC0f1uOVL6wdrmZBMXuts5bPeKq6pO1/8Knh2W+VJfvuFhAWfOfDXq7zpVHfPLXQMc3RQT/rpoge+3EeuQMcdeXnUvSTWuzulzxKdxAoIMywstPyVzVTWSvzvPj7C/zdjbZglQ+LUIySt13gBp2f6LSpnwKytfr6KYs/bwoF/cDVm7Mb++5rDlyy7ogbd7AeqrxVkh6EV34YYxmuWkVQoO8jFs5n8hLi9EccdnL03qLrajrLnPffEb9e3VFaqWX+0wLFh6CsrC14vGHnMv+/zKVf6TC7Lmp5bzR9ihS8aoPkbpE/N1yRIhi+WXx/1bBs7TWoM=
  - secure: IbPBtfexRuT0Nl8HnnysWhdd4v4o6MfRpZMu7a1P3dEmAOyUTnyoqDtWHRQVLJizLHJTzXSJGyilGY4Y5SAycpg8g/XrBD2c/7n4KbLs0xXIuTu/J/Mg/YKD103iQx1f00vo7Sv9aVJV2jubDBWKC8HWq3V+/3PxCc5R4fNPqirbb5dpjbq2bOZN1WVwnmioVwUUxc1B4+3PzbLLJNFjOrfCo8rn0atgCEw46SIItS3IVu1DlkBcZeWuEHJHZki2bR6540XtuaN7Xl+mnABYG+fSv2tZNX5rEKxSnGfL8lQybx5z/DSOo3NjvxIEmJGYnMBadD3GzGCeRMoNb1FKDQcxYEPJlNtt1SSod7ffAsvZjVdd6S4jBK99B7B2fyZktqD2/zSz97UD+wW4moMlIbRMb+4JbxJ8rX+4QsMkJ2DX1HU7WTdSjTmyyVVfgeWRrJPquKZiw7yyn07rih0bbfm8XdjEnICoNedCs6MVFExwPb9e0IDY9DUpJfrrc5QZhl2FqPJply+wpwGkFQYFqehASo1BFe2dxT+/3YhXCRLZlCrjyCvlDmk4iXogUVUVWZWx919w/UXvwFdewbJyQy6CQB2O7wR4cjkWK2RLAEeOnBMCM4Te32IcegHhgEViOcsK2W5pjaEZBzT5StpE3f0h/Fc6eQDX8Ngd2iRG/nU=
deploy:
  provider: releases
  api_key:
    secure: JYtmSzjFysF/3NCxlVCmlX92m7dZOpFt5zxb4w9j3E15k/nXkg48PK5rh7BBnTsmFV5cHGYn85Kj7MDcCnBCO77kfp1ceLvlL5I6V4q8TNrnFaUrtPyIrNNhOnCtO1OGtHM06RdCYI8mEZYavQ+rGvWyUi4rjLaerpAbAAtziYC07+BZa6iPg6VhfmIvSnizZXRJVOvxYoZ8G7ddU/c9oOvWQmfDzNEbPbi5MFnM9l9wqyz93G+PZzarseiVdntMRc9Kr4m5PsCtLwzmeHZBIEfY8xEiFqpmUGS6ssqepEh+yXv4QwfiFx4LYRaRxQS/ObC36vkd3aEVtro7UdPhOXGsoX4XFLlHNk5Z42jUwk/pdFEUWWdamgydCOuzWj0toDlApnBSSk1M8I+8VowPu6g5DJ9AnvZRuxM/hm1OrMUyIc4ETu+fZGKNYoS/Zhp/Y8TjhQSuCyP3o/xoCTnrJtSjLZJVO0g11CHiUz78xqRhFfrThb6obEKEWuN7KewHXCiIAW+Gmj+LuapS3MAu+QyJCRNnwuvtmV8C7mEe4I2+/O4AVXqq7PJDIp7PuWdtoOPVsz7mURdN6oLDoMMQ8DIB5PkhTW7foQV1Clr4+hZCDk5BrU1lvwbPLPQhZzBm7NKJKJ3jzmUo6MEAncHxUNiQfD0LzBMlyAv8xIHVrfM=
  file: kdtool-${TRAVIS_TAG}.pyz
  skip_cleanup: true
  on:
    repo: torchbox/kdtool
    tags: true
